name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
  APP_NAME: gaargok8s

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub marcoliew
      uses: docker/login-action@v3
      with:
        username: ${DOCKER_USERNAME}
        password: ${DOCKERHUB_TOKEN}
      
    - name: Build the Docker image
      run: |
        docker build . --file docker/Dockerfile --tag ${DOCKER_USERNAME}/${APP_NAME}:latest
        docker push ${DOCKER_USERNAME}/${APP_NAME}:latest
