name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
  APP_NAME: gaargok8s

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub marcoliew
      uses: actions/checkout@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag $APP_NAME:$(date +%s)
