name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  #DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
  APP_NAME: gaargok8s
  USER_NAME: marcoliew
  X: date +%s

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    # - name: Checkout code
    #   uses: actions/checkout@v3

    - name: Login to Docker Hub marcoliew
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    # - name: Build the Docker image
    #   run: |
    #     docker build . --file docker/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/${APP_NAME}:latest
    #     docker push ${{ secrets.DOCKER_USERNAME }}/${APP_NAME}:latest


    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    - name: Build the app image
      uses: docker/build-push-action@v5
      with:
        push: true
        context: "{{defaultContext}}:docker"
        file: Dockerfile
        platforms: linux/amd64
        tags: marcoliew/gaargok8s:${X}
        #tags: ${USER_NAME}}/${APP_NAME}}:latest
        # secrets: |
        #   "username=${{ secrets.DOCKERHUB_USERNAME }}"
        #   "password=${{ secrets.DOCKERHUB_TOKEN }}"    